import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import { Footer } from '../Footer/Footer.tsx';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Netflix roulette',
	description: 'Generated by create next app'
};

export default function RootLayout({ children,  }: {
	children: React.ReactNode,
}) {


	return (
		<html lang="en">
		<body className={inter.className}>
		{children}
		<div id="overlay"></div>
		<Footer/>
		</body>
		</html>
	);
}
